config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'

  get 'home/about' => 'homes#about'

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:show, :edit, :update, :index] do
  resource :relationships, only: [:create, :destroy]
  # post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  # post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'following_user' => 'relationships#following_user'
  get 'follower_user' => 'relationships#follower_user'
  end

  get '/search', to: 'searches#search'
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    @comment = BookComment.new(book_comment_params)
    @comment.user_id = current_user.id
    @comment.book_id = @book.id
    @comment.save

    # redirect_to book_path(book)
  end

  def destroy
    # BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    # redirect_to book_path(params[:book_id])
    @book = Book.find(params[:book_id])
    book_comment = @book.book_comments.find(params[:id])
    book_comment.destroy
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_comments.html.erb
<% books.book_comments.each do |book_comment| %>
  <tr>
    <td><%= attachment_image_tag book_comment.user, :profile_image, :fill, 100, 100, fallback: "no-image.jpg" %><br>
    <%= link_to book_comment.user.name, user_path(book_comment.user.id) %></td>

    <td><%= book_comment.comment %></td>

    <% if book_comment.user == current_user %>
      <td><%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, remote: true %></td>
    <% end %>
  </tr>
<% end %>

app/views/book_comments/create.js.erb
$("#book_<%= @book.id %> .comments-count").html("コメント数: <%= @book.book_comments.count %>");
$(".book_comments").html("<%= j(render 'book_comments/comments', book: @book) %>");
$("#book_comment_comment").val("");

app/views/book_comments/destroy.js.erb
$("#book_<%= @book.id %> .comments-count").html("コメント数: <%= @book.book_comments.count %>");
$(".book_comments").html("<%= j(render 'book_comments/comments', book: @book) %>");
$("#book_comment_comment").val("");