config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'

  get 'home/about' => 'homes#about'

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:show, :edit, :update, :index] do
  resource :relationships, only: [:create, :destroy]
  # post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  # post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'following_user' => 'relationships#following_user'
  get 'follower_user' => 'relationships#follower_user'
  end

  get '/search', to: 'searches#search'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        # :authentication_keys => [:username]

  validates :name, presence: true
  validates :name, length: { in: 2..20  }
  validates :name, uniqueness: true

  validates :introduction, length: { maximum: 50 }

  # def self.find_first_by_auth_conditions(warden_conditions)
  #   conditions = warden_conditions.dup
  #   if login = conditions.delete(:login)
  #     #認証の条件式を変更する
  #     where(conditions).where(["name = :value", { :value => name }]).first
  #   else
  #     where(conditions).first
  #   end
  # end

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  # 自分がフォローする（与フォロー）側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "follow_id", dependent: :destroy # フォロー取得/suru
  # 自分がフォローされる（被フォロー）側の関係性
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得/sareru

  # 与フォロー関係を通じて参照→自分がフォローしている人
  has_many :following_user, through: :relationships, source: :followed # 自分がフォローしている人
  # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :follower_user, through: :reverse_of_relationships, source: :follow # 自分をフォローしている人

  # ユーザーをフォローする
  def follow(user_id)
  relationships.create(followed_id: user_id)
  end

# ユーザーのフォローを外す
  def unfollow(user_id)
  relationships.find_by(followed_id: user_id).destroy
  end

# フォローしていればtrueを返す
  def following?(user)
  following_user.include?(user)
  end


  # def self.looks(search, word)
  #   if search == "perfect_match"
  #     @user = User.where("name LIKE?", "#{word}")
  #   elsif search == "forward_match"
  #     @user = User.where("name LIKE?","#{word}%")
  #   elsif search == "backward_match"
  #     @user = User.where("name LIKE?","%#{word}")
  #   elsif search == "partial_match"
  #     @user = User.where("name LIKE?","%#{word}%")
  #   else
  #     @user = User.all
  #   end
  # end

  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
  end


  attachment :profile_image

  validates :name, presence: true


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!, only: [:edit, :index, :show]

def authenticate_user!
       unless user_signed_in?
        redirect_to new_user_session_path
       end
end

  def show
    @book = Book.new
    @user = User.find(params[:id])
  end

  def index
    @book = Book.new
    # @user = current_user
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render :edit
    end
  end
  
  

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_side.html.erb
<h2>User info</h2>
<%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no-image.jpg" %>
<table class="table">
  <tr>
    <th>name</th>
    <th><%= user.name %></th>
  </tr>
  <tr>
    <th>introduction</th>
    <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th>

    <%= link_to user_following_user_path(user.id) do %>
    <%= user.following_user.count %>
    <% end %>

    </th>
  </tr>
  <tr>
    <th>followers</th>
    <th>
    <%= link_to user_follower_user_path(user.id) do %>
    <%= user.follower_user.count %>
    <% end %>
    </th>
  </tr>
</table>
<!--復習部分-->
<% if user == current_user %>
  <%= link_to  edit_user_path(user), class: 'btn btn-outline-secondary btn-block' do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
<% else %>
  <% if current_user.following?(user) %>
    <%= link_to 'フォロー外す', user_relationships_path(user.id), class: 'action', method: :delete %>
  <% else %>
    <%= link_to 'フォローする', user_relationships_path(user.id), class: 'action',  method: :POST %>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<div class="container">
     <div class="row">
          <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
<%= form_with model:@user, local:true do |f| %>
<h2>User info</h2>
<% if @user.errors.any? %>
     <p><%= @user.errors.count %>errors prohibited this book from being saved:</p>
     <% @user.errors.full_messages.each do |user| %>
          <p><%= user %> can't be blank.</p>
    <% end %>
 <% end %>
<div class="field">
<label>Name</label>
<%= f.text_field :name, class: "user-form", autofocus: true, id:"inputname", placeholder:"名前" %>
</div>
<div class="field">
<label>Image</label>
<%= f.attachment_field :profile_image, class: "user-image-form", placeholder: "プロフィール画像" %>
</div>
<div class="field">
<label>Introduction</label>
<%= f.text_area :introduction, class: "user-form" %>
</div>
<%= f.submit "Update User", class: "action" %>
<% end %>
</div>
</div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
       <%= render 'users/side', user: current_user %>
       <%= render 'books/side', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
          <h2>Users</h2>
          <table class="table">
            <thead>
              <tr>
                <th>image</th>
                <th>name</th>
                <th colspan="3"></th>
              </tr>
            </thead>
        <% @users.each do |user| %>
            <tbody>
              <tr>
                <td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no-image.jpg" %></td>
                <td><%= user.name %></td>
                <td><%= "フォロー数: #{user.following_user.count}" %></td>
                <td><%= "フォロワー数: #{user.follower_user.count}" %></td>


                <% if current_user.following?(user) %>
                <td><%= link_to 'フォロー外す', user_relationships_path(user.id), method: :delete %></td>
                <% else %>
                <td><%= link_to 'フォローする', user_relationships_path(user.id), method: :POST %></td>
                <% end %>

                <td><%= link_to "Show", user_path(user.id) %></td>
              </tr>
            </tbody>
            <% end %>
          </table>

    </div>
  </div>
</div>

app/views/users/show.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/side', user: @user %>
      <%= render 'books/side', book: @book %>
    </div>
<!--下記復習-->
    <div class="col-md-8 offset-md-1">
     <h2>Books</h2>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <!--<th colspan="3"></th>-->
          </tr>
        </thead>
        <% @user.books.each do |book| %>
        <tbody>
          <tr>
              <td><%= link_to attachment_image_tag(book.user, :profile_image, :fill, 60, 60, fallback: "no-image.jpg"), user_path(book.user) %></td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>