config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'

  get 'home/about' => 'homes#about'

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:show, :edit, :update, :index] do
  resource :relationships, only: [:create, :destroy]
  # post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  # post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'following_user' => 'relationships#following_user'
  get 'follower_user' => 'relationships#follower_user'
  end

  get '/search', to: 'searches#search'
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  has_many :favorites, dependent: :destroy
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: { maximum: 200 }

# 　# 検索方法分岐
#   def self.looks(search, word)
#     if search == "perfect_match"
#       @book = Book.where("title LIKE?","#{word}")
#     elsif search == "forward_match"
#       @book = Book.where("title LIKE?","#{word}%")
#     elsif search == "backward_match"
#       @book = Book.where("title LIKE?","%#{word}")
#     elsif search == "partial_match"
#       @book = Book.where("title LIKE?","%#{word}%")
#     else
#       @book = Book.all
#     end
#   end

  def self.search_for(content, method)
    if method == 'perfect'
      Book.where(title: content)
    elsif method == 'forward'
      Book.where('title LIKE ?', content+'%')
    elsif method == 'backward'
      Book.where('title LIKE ?', '%'+content)
    else
      Book.where('title LIKE ?', '%'+content+'%')
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :authenticate_user!, only: [:edit, :index, :show]

before_action :correct_post,only: [:edit]

def authenticate_user!
       unless user_signed_in?
        redirect_to new_user_session_path
       end
end

def correct_post
        @book = Book.find(params[:id])
    unless @book.user.id == current_user.id
      redirect_to books_path
    end
end

  def index
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: "Book was successfully created"
    else
      @books = Book.all
      render :index
    end
  end

  def show
    @new_book = Book.new
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
    # Nに値するbookのuser_idカラムをもとにUserからuse.idを探す
    # @user = User.find(params[:user_id])
    # @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
  end

  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: "You have updated book successfully."
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.user.id = current_user.id
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_side.html.erb
<h2>New book</h2>
<%= form_with model:book, local:true do |f| %>
<div class="field">
  <lavel class="book-title">Title</lavel>
  <%= f.text_field :title, class: "book-form" %>
</div>

<div class="field">
  <lavel class="book-body">Opinion</lavel>
  <%= f.text_area :body, class: "book-form" %>
</div>

<div class="field">
<%= f.submit "Create Book", class: "action" %>
</div>
<% end %>

app/views/books/edit.html.erb
<div class="container">
    <div class ="row">
        <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

<h1>Editing Book</h1>
<%= form_with model:@book, local:true do |f| %>

<% if @book.errors.any? %>
     <p><%= @book.errors.count %>errors prohibited this book from being saved:</p>
     <% @book.errors.full_messages.each do |book| %>
          <p><%= book %> can't be blank.</p>
    <% end %>
 <% end %>

  <div class="field">
    <lavel>Title</lavel>
    <%= f.text_field :title, class: "book-form" %>
  </div>

  <div class="field">
    <lavel>Opinion</lavel>
    <%= f.text_area :body, class: "book-form" %>
  </div>
    <%= f.submit "Update Book", class: "action" %>
<% end %>

<%= link_to "Show", book_path(@book.id) %> |
<%= link_to "Back", books_path %>
</div>
</div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm -0">
  <div class="row">
    <div class="col-md-3">
      <% if @book.errors.any? %>
        <p><%= @book.errors.count %>errors prohibited this book from being saved:</p>
        <% @book.errors.full_messages.each do |book| %>
          <p><%= book %> can't be blank.</p>
        <% end %>
      <% end %>
    <%= render 'users/side', user: current_user %>
    <%= render 'books/side', book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <!--<th colspan="3"></th>-->
            </tr>
          </thead>
        <% @books.each do |book| %>
          <tbody>
            <tr id="book_<%= book.id %>">

                <td><%= link_to attachment_image_tag(book.user, :profile_image, :fill, 60, 60, fallback: "no-image.jpg"), user_path(book.user) %></td>

              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>

              <!--いいね機能-->
              <td class="favorites"><%= render 'favorites/favorites', book: book %></td>

              <!--コメント機能-->
              <td class="comments-count"><p>コメント数:<%= book.book_comments.count %></p></td>
            </tr>
          </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>
<div class="container">
    <div class="row">
        <div class="col-md-3">

          <%= render 'users/side', user: @book.user %>
          <%= render 'books/side', book: @new_book %>
        </div>

        <div class="col-md-8 offset-md-1">
          <h2>Book detail</h2>
          <table class="table">
            <tbody>
              <tr id="book_<%= @book.id %>">
                <td><%= attachment_image_tag @book.user, :profile_image, :fill, 100, 100, fallback: "no-image.jpg" %><br>
                <%= link_to @book.user.name, user_path(@book.user.id) %></td>
                        <!--@user.name-->
                <td><%= @book.title %></td>
                <td><%= @book.body %></td>



          <!--復習部分-->
              <% if @book.user.id == current_user.id %>

              <td><%=link_to "Edit", edit_book_path(@book.id), class: "action" %></td>
              <td><%=link_to "Destroy", book_path(@book.id),method: :delete, "data-confirm" => "本当に消しますか？", class: "destroy-action" %></td>

              <% else %>
                <td class="favorites"><%= render 'favorites/favorites', book: @book %></td>

              <td class="comments-count"><p>コメント件数:<%= @book.book_comments.count %></p></td>
              <% end %>
              </tr>
              
              <!--コメント・いいね下記追加部分-->
              <td class="book_comments"><%= render 'book_comments/comments', books: @book %></td>

              


            </tbody>
          </table>
          <%= form_with(model:[@book, @book_comment], local: true) do |f| %>
          <div class="field">
              <%= f.text_area :comment, class: "w-100" %>
              <%= f.submit "送信", class: "action", rows: '5' %>
          </div>
          <% end %>
        </div>
    </div>
</div>