config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'

  get 'home/about' => 'homes#about'

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:show, :edit, :update, :index] do
  resource :relationships, only: [:create, :destroy]
  # post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  # post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'following_user' => 'relationships#following_user'
  get 'follower_user' => 'relationships#follower_user'
  end

  get '/search', to: 'searches#search'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KADAI3Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/93b338d458.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <header>
   <nav class="navber">
     <div class="container">
         <div class="row">
         <div class="col-auto mr-auto">
         <%= link_to "Bookers", root_path, class: "home-title" %>
         </div>
         <div class= "col-auto">
       <% if user_signed_in? %>
         <li class="col-md-1">
           <!--<i class="fas fa-home"></i>-->
           <%= link_to(content_tag(:i, 'Home', class: 'fas fa-home header-item'), user_path(current_user.id)) %>
         </li>
         <li class="col-md-1">
           <!--<i class="fas fa-users"></i>-->
           <%= link_to(content_tag(:i, 'Users', class: 'fas fa-users header-item'), users_path) %>
         </li>
         <li class="col-md-1">
           <!--<i class="fas fa-book-open"></i>-->
           <%= link_to(content_tag(:i, 'Books', class: 'fas fa-book-open header-item'), books_path) %>
         </li>
         <li class="col-md-1">
           <!--<i class="fas fa-sign-out-alt"></i>-->
            <!--link_to "ログアウト", class="fas fa-sign-out-alt", destroy_user_session_path, method: :delete -->
           <%= link_to(content_tag(:i, 'logout', class: 'fas fa-sign-out-alt header-item'), destroy_user_session_path, :method => :delete) %>
         </li>
       <% else %>
         <li>
           <!--<i class="fas fa-home"></i>-->
           <%= link_to(content_tag(:i, 'Home', class: 'fas fa-home header-item'), root_path) %>
         </li>
         <li>
           <!--<i class="fas fa-link"></i>-->
           <%= link_to(content_tag(:i, 'About', class: 'fas fa-link header-item'), home_about_path) %>
         </li>
         <li>
           <!--<i class="fas fa-user-plus"></i>-->
           <%= link_to(content_tag(:i, 'sign up', class: 'fas fa-user-plus header-item'), new_user_registration_path) %>
         </li>
         <li>
           <!--<i class="fas fa-sign-in-alt"></i>-->
           <%= link_to(content_tag(:i, 'login', class: 'fas fa-sign-in-alt header-item'), new_user_session_path) %>
         </li>
       <% end %>
       </div>
       </div>
     </div>
    </nav>
    </header>
    <main>
        <% if user_signed_in? %>
          <%= render 'searches/form' %>
        <% end %>
        <p id="notice"><%= notice %></p>
        <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>